# Generated by Django 6.0.6 on 2026-07-02 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('long_name', models.CharField(max_length=128)),
                ('color', models.CharField(blank=True, max_length=6)),
                ('route_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(db_index=True, max_length=64)),
                ('trip_id', models.CharField(blank=True, max_length=64)),
                ('direction_id', models.IntegerField(null=True)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('departure_time', models.DateTimeField(null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='transit.route')),
            ],
            options={
                'indexes': [models.Index(fields=['stop_id', 'recorded_at'], name='transit_pre_stop_id_5c27a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(db_index=True, max_length=64)),
                ('stop_id', models.CharField(blank=True, max_length=64)),
                ('current_status', models.CharField(max_length=32)),
                ('direction_id', models.IntegerField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bearing', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='transit.route')),
            ],
            options={
                'indexes': [models.Index(fields=['route', 'recorded_at'], name='transit_veh_route_i_d85e11_idx')],
            },
        ),
    ]
