# Generated by Django 6.0.6 on 2026-07-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesnapshot',
            name='trip_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
